// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import "package:firebase_core/firebase_core.dart" show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAc4g75yWtfwVfu5SX_r2b-DPccrpH5Wmw',
    appId: '1:667840697792:web:e6a977e40e2b0e2f94a425',
    messagingSenderId: '667840697792',
    projectId: 'benafood-985ef',
    authDomain: 'benafood-985ef.firebaseapp.com',
    storageBucket: 'benafood-985ef.firebasestorage.app',
    measurementId: 'G-3Z098WFXBH',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYqbbn5DnhIbiL9P_WbtUCO0_Vpwd4qTk',
    appId: '1:667840697792:android:7772211c5fc8f7ea94a425',
    messagingSenderId: '667840697792',
    projectId: 'benafood-985ef',
    storageBucket: 'benafood-985ef.firebasestorage.app',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXe5FmFF2qsyb4I165zVCD4Wp0niVRUJk',
    appId: '1:667840697792:ios:14d6537c54bd236794a425',
    messagingSenderId: '667840697792',
    projectId: 'benafood-985ef',
    storageBucket: 'benafood-985ef.firebasestorage.app',
    iosBundleId: 'com.example.benaFood',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXe5FmFF2qsyb4I165zVCD4Wp0niVRUJk',
    appId: '1:667840697792:ios:14d6537c54bd236794a425',
    messagingSenderId: '667840697792',
    projectId: 'benafood-985ef',
    storageBucket: 'benafood-985ef.firebasestorage.app',
    iosBundleId: 'com.example.benaFood',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAc4g75yWtfwVfu5SX_r2b-DPccrpH5Wmw',
    appId: '1:667840697792:web:40df7c99728e9e6e94a425',
    messagingSenderId: '667840697792',
    projectId: 'benafood-985ef',
    authDomain: 'benafood-985ef.firebaseapp.com',
    storageBucket: 'benafood-985ef.firebasestorage.app',
    measurementId: 'G-XFDWM8PKHV',
  );
}
